# 工作流名称
name: Sync and Convert Proxy Rules

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# 任务
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：下载、转换并保存规则文件
      - name: Download and Convert Rules
        run: |
          mkdir -p rules
          
          # GPTs
          curl -sL "https://github.com/SouthernHU/proxyRules/raw/refs/heads/main/behavior_classical/GPTs.list" | \
          grep -v -E '^(#|$|PROCESS-NAME|USER-AGENT|no-resolve|DST-PORT)' | \
          sed \
            -e 's/,full:/,/' \
            -e 's/^DOMAIN-SUFFIX,/HOST-SUFFIX,/' \
            -e 's/^DOMAIN,/HOST,/' \
            -e 's/^DOMAIN-KEYWORD,/HOST-KEYWORD,/' \
            -e 's/$/,proxy/' \
          > GPTs.list
          # GFWPatch
          curl -sL "https://github.com/SouthernHU/proxyRules/raw/refs/heads/main/behavior_classical/GFWPatch.list" | \
          grep -v -E '^(#|$|PROCESS-NAME|USER-AGENT|no-resolve|DST-PORT)' | \
          sed \
            -e 's/,full:/,/' \
            -e 's/^DOMAIN-SUFFIX,/HOST-SUFFIX,/' \
            -e 's/^DOMAIN,/HOST,/' \
            -e 's/^DOMAIN-KEYWORD,/HOST-KEYWORD,/' \
            -e 's/$/,proxy/' \
          > GFWPatch.list
          # GFWLite
          curl -sL "https://github.com/SouthernHU/proxyRules/raw/refs/heads/main/behavior_classical/GFWLite.list" | \
          grep -v -E '^(#|$|PROCESS-NAME|USER-AGENT|no-resolve|DST-PORT)' | \
          sed \
            -e 's/,full:/,/' \
            -e 's/^DOMAIN-SUFFIX,/HOST-SUFFIX,/' \
            -e 's/^DOMAIN,/HOST,/' \
            -e 's/^DOMAIN-KEYWORD,/HOST-KEYWORD,/' \
            -e 's/$/,proxy/' \
          > GFWLite.list


          # ChinaDomainLite
          curl -sL "https://raw.githubusercontent.com/SouthernHU/proxyRules/refs/heads/main/behavior_classical/ChinaDomainLite.list" | \
          grep -v -E '^(#|$|PROCESS-NAME|USER-AGENT|no-resolve|DST-PORT)' | \
          sed \
            -e 's/,full:/,/' \
            -e 's/^DOMAIN-SUFFIX,/HOST-SUFFIX,/' \
            -e 's/^DOMAIN,/HOST,/' \
            -e 's/^DOMAIN-KEYWORD,/HOST-KEYWORD,/' \
            -e 's/$/,DIRECT/' \
          > ChinaDomainLite.list

      # 第三步：提交并推送到你的仓库（使用更稳健的方式）
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # 仅在文件有变动时才执行提交和推送
          if git status --porcelain | grep .; then
            git commit -m "chore: auto-update rules by GitHub Actions"
            git pull origin main --rebase
            git push
          else
            echo "No changes to commit."
          fi

