# 工作流名称
name: Sync and Convert Proxy Rules

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# 任务
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Convert Rules
        run: |
          mkdir -p rules
          
          # 下载原始规则文件，然后进行转换
          # 1. curl -sL 下载文件
          # 2. sed 命令进行多重替换：
          #    -e 's/^RULE_TYPE,/new_rule_type,/'  <- 替换规则类型
          #    ...
          #    -e 's/$/,proxy/'  <- ❗❗❗ 核心改动：在每一行末尾追加策略 ",proxy"
          curl -sL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list" | \
          # 移除PROCESS-NAME规则
          grep -v -E '^(#|$|PROCESS-NAME)' | \
          sed \
            -e 's/^DOMAIN-SUFFIX,/HOST-SUFFIX,/' \
            -e 's/^DOMAIN,/HOST,/' \
            -e 's/^DOMAIN-KEYWORD,/HOST-KEYWORD,/' \
          # -e 's/$/,proxy/' \
          > rules/ProxyGFWlist_qx.list

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-update rules by GitHub Actions" || exit 0
          git push
